export const FETCH_TEACHER_REQUEST="FETCH_TEACHER_REQUEST";
export const FETCH_TEACHER_SUCCESS="FETCH_TEACHER_SUCCESS";
export const FETCH_TEACHER_FAILURE="FETCH_TEACHER_FAILURE";
export const FETCH_TEACHER_DELETE="FETCH_TEACHER_DELETE";
