export const FETCH_COURSE_REQUEST="FETCH_COURSE_REQUEST";
export const FETCH_COURSE_SUCCESS="FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILURE="FETCH_COURSE_FAILURE";
export const FETCH_COURSE_DELETE="FETCH_COURSE_DELETE";
export const FETCH_COURSE_EDIT="FETCH_COURSE_EDIT";


